---

- hosts: storm-master

  vars_prompt:
   - name: "user_password"    
     prompt: "Enter a password for the stormcrawler user"    
     private: yes    
     encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it    
     confirm: yes    
     salt_size: 7

  tasks:
   - name: Create StormCrawler User
     user: name=stormcrawler createhome=true group=storm password="{{user_password}}"

   - apt: 
      name: curl
      state: present
      update_cache: yes

   - apt: 
      name: git
      state: present
      update_cache: yes

   - apt: 
      name: maven
      state: present
      update_cache: yes
