---

- hosts: storm-master
  become: yes
  remote_user: root

  tasks:

   - name: Create StormCrawler User
     user: name=stormcrawler createhome=true group=storm

   - apt: 
      name: curl
      state: installed
      update_cache: yes

   - apt: 
      name: git
      state: installed
      update_cache: yes

   - apt: 
      name: maven
      state: installed
      update_cache: yes


- hosts: storm-slave
  become: yes
  remote_user: root

  tasks:

  - file:
       path: /output
       owner: storm
       group: storm
       state: directory
       mode: "u=rwx,g=rwx,o=rwx"
       recurse: yes

