---

- hosts: storm-slave
  become: yes
  remote_user: root
  vars: 
    master_ip: 149.202.201.195
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_port: 9200
    es_version: "5.3.1"
    es_heap_size: 10g

  pre_tasks:
   - file:
       path: /var/log/elasticsearch
       state: absent

   - file:
       path: /data1/elasticsearch
       state: absent

   - file:
       path: /data2/elasticsearch
       state: absent

  roles:
    - { role: elasticsearch, es_instance_name: "es_node", es_data_dirs: "/data1/elasticsearch,/data2/elasticsearch", es_log_dir: "/var/log/elasticsearch",
    es_config: {
        discovery.zen.ping.unicast.hosts: "{{master_ip}}:9300",
        http.port: 9200,
        network.host: ["_local_","_global_"],
        network.publish_host: "_global_",
        transport.tcp.port: 9300,
        node.data: true,
        bootstrap.memory_lock: false,
        cluster.name: "crawler"
        } 
    }


- hosts: storm-master
  become: yes
  remote_user: root
  vars: 
    es_version: "5.3.1"

  tasks:
   - apt: 
      name: kibana={{es_version}}
      state: installed
      update_cache: yes

   - systemd: state=started name=kibana daemon_reload=yes
