---
 
- hosts: storm-slave
  vars: 
    storm_version: 1.2.2
    master_ip: localhost

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

  tasks:
   - name: add repo for java 8
     apt_repository: repo='ppa:webupd8team/java' state=present

   - debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

   - name: install java 8
     apt: name=oracle-java8-installer state=latest update-cache=yes force=yes

   - group: name=storm system=yes state=present

   - name: Create Storm User
     user: name=storm system=yes createhome=false group=storm

   - unarchive: 
       src: "http://www.mirrorservice.org/sites/ftp.apache.org/storm/apache-storm-{{ storm_version }}/apache-storm-{{ storm_version }}.tar.gz"
       dest: /usr/share/
       remote_src: True
       owner: storm
       group: storm

   - file:
       path: "/usr/share/apache-storm-{{ storm_version }}"
       owner: "storm"
       group: "storm"
       mode: "u=rwx,g=rwx,o=r"
       recurse: yes
       state: directory

   - file:
       src: "/usr/share/apache-storm-{{ storm_version }}/bin/storm"
       dest: /usr/bin/storm
       owner: storm
       group: storm
       state: link

   - file:
       path: /var/log/storm
       owner: storm
       group: storm
       state: directory
       mode: "u=rwx,g=rwx,o=r"
       recurse: yes

   - file:
       path: /var/log/storm/workers-artifacts/
       owner: storm
       group: storm
       state: directory
       mode: "u=rwx,g=rwx,o=rwx"
       recurse: yes

   - template: src=Files/storm.yaml dest="/usr/share/apache-storm-{{ storm_version }}/conf/storm.yaml"

   - template: src=Files/stormservicetemplate dest="/etc/systemd/system/storm-{{ item }}.service"
     with_items:
        - supervisor

   - systemd: state=started name=storm-{{ item }}.service daemon_reload=yes
     with_items:
        - supervisor


- hosts: storm-master
  vars: 
    storm_version: 1.2.2

  tasks:
   - name: Install Zookeeperd
     apt: pkg=zookeeperd state=present update_cache=true

   - template: src=Files/stormservicetemplate dest="/etc/systemd/system/storm-{{ item }}.service"
     with_items:
        - nimbus
        - ui

   - systemd: state=started name=storm-{{ item }}.service daemon_reload=yes
     with_items:
        - nimbus
        - ui


